---
- hosts: webservers
  remote_user: root

- name: provision test instances
  hosts: localhost
  vars_files:
  - var.yml
  vars:
    ansible_python_interpreter: "/usr/bin/env python"

  tasks:
    - name: create volumes
      os_volume:
        state: present
        size: 30
        display_name: "{{ item }}"    
        cloud: beebop
      register: '{{ item }}_volume'
      with_items: "{{ instance_names }}"

    - include: keypair.yml

    - name: Get bootstrap token for etcd
      command: curl -w "\n" https://discovery.etcd.io/new
      register: token
    - debug: msg="Etcd token is {{ token.stdout }}"

    - name: create the security group
      os_security_group:
        cloud: beebop
        name: "{{ security_groups }}"
        description: "{{ instance_prefix }} {{ security_groups_description }}"
        state: present
      register: security_group

    - name: create security group rules
      os_security_group_rule:
        cloud: beebop
        security_group: "{{ security_groups }}"
        protocol: "{{ item.proto | default(omit) }}"
        port_range_min: "{{ item.port | default(omit) }}"
        port_range_max: "{{ item.port | default(omit) }}"
        remote_ip_prefix: "{{ item.cidr | default(omit) }}"
        remote_group: "{{ item.group | default(omit) }}"
        ethertype: "{{ item.ethertype | default(omit) }}"
        state: present
      with_items: "{{ security_group_rules }}"
 
    - name: create instances
      os_server:
        cloud: beebop
        name: "{{ item }}"
        image: "{{ image_id }}"
        key_name: ansible
        wait: yes
        timeout: 200
        flavor: "{{ flavor }}"
        nics:
          - net-name: "mosorio_net"
        auto_ip: True
        boot_from_volume: True
        volume_size: 10
        volumes:
          - "{{ item }}"

        userdata: |
          #cloud-config
          coreos:
            etcd2:
              name: {{ item }}
              discovery: {{token.stdout}}
              advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
              initial-advertise-peer-urls: http://$private_ipv4:2380
              listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
              listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
            units:
              - name: format-ephemeral.service
                command: start
                content: |
                  [Unit]
                  Description=Formats the ephemeral drive
                  After=dev-sdb.device
                  Requires=dev-sdb.device
                  [Service]
                  Type=oneshot
                  RemainAfterExit=yes
                  ExecStart=/usr/sbin/wipefs -f /dev/sdb
                  ExecStart=/usr/sbin/mkfs.ext4 -F /dev/sdb
              - name: var-lib-docker.mount
                command: start
                content: |
                  [Unit]
                  Description=Mount ephemeral to /var/lib/docker
                  Requires=format-ephemeral.service
                  After=format-ephemeral.service
                  [Mount]
                  What=/dev/sdb
                  Where=/var/lib/docker
                  Type=ext4
              - name: docker.service
                drop-ins:
                  - name: 10-wait-docker.conf
                    content: |
                      [Unit]
                      After=var-lib-docker.mount
                      Requires=var-lib-docker.mount
              - name: etcd2.service
                command: start
              - name: fleet.service
                command: start
              - name: docker.service
                drop-ins:
                  - name: "20-mirror-registry.conf"
                    content: |
                      [Service]
                      Environment=DOCKER_OPTS='--registry-mirror=https://registry.beebop.cloud --add-registry=https://registry.beebop.cloud'
              - name: docker.service
                command: start
      with_items: "{{ instance_names }}"
      register: instances